/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FishyBusiness (https://sketchfab.com/FishyBusiness)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/retro-computer-v2-58a3890be360441cad5d5c089ccc3b32
title: Retro Computer V2
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Computer({ ...props }) {
  const [yRotation, setYRotation] = useState(0);
  useEffect(() => {
    const interval = setInterval(() => {
      setYRotation(yRotation + 0.01);
    }, 10);
    return () => clearInterval(interval);
  });

  const group = useRef();
  const { nodes, materials } = useGLTF('/computer.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group
          scale={5}
          rotation={[Math.PI / 2, yRotation, 0]}
          position={[0, 0, -1]}
        >
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.material_0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/computer.gltf');
